from __future__ import annotations

# ruff: noqa: F401
# Legacy compatibility facade. New code should import from config, markdown,
# mermaid, pdf or cli directly.
from .config import (
    DEFAULT_INPUT,
    DEFAULT_OUTPUT,
    FONT_BOLD,
    FONT_CANDIDATES,
    FONT_REGULAR,
    MERMAID_COUNTER,
    MERMAID_DIR,
    PARAGRAPH_INDENT,
    QUIET,
    ROOT,
    VERSION,
    pick_font,
    register_fonts,
    set_mermaid_dir,
    set_quiet,
)
from .markdown import (
    add_table,
    clean_heading,
    clean_inline,
    column_widths,
    flush_bullets,
    flush_paragraph,
    is_table_divider,
    make_cell,
    split_table_row,
)
from .mermaid import (
    base_canvas,
    cleanup_mermaid_dir,
    crop_mermaid_png,
    draw_arrow,
    draw_box,
    draw_dashed_vertical,
    draw_sequence_arrow,
    extract_mermaid_label,
    load_font,
    parse_edges,
    prepare_mermaid_for_pdf,
    render_flowchart,
    render_mermaid_image,
    render_mermaid_with_cli,
    render_sequence,
    render_state,
    render_xychart,
    resolve_mermaid_viewport,
    text_size,
    try_render_mermaid_with_cli,
    wrap_text,
)
from .pdf import PdfOptions, build_pdf, flush_code

__all__ = [
    "DEFAULT_INPUT",
    "DEFAULT_OUTPUT",
    "FONT_BOLD",
    "FONT_CANDIDATES",
    "FONT_REGULAR",
    "MERMAID_COUNTER",
    "MERMAID_DIR",
    "PARAGRAPH_INDENT",
    "PdfOptions",
    "QUIET",
    "ROOT",
    "VERSION",
    "add_table",
    "base_canvas",
    "build_pdf",
    "clean_heading",
    "clean_inline",
    "cleanup_mermaid_dir",
    "column_widths",
    "crop_mermaid_png",
    "draw_arrow",
    "draw_box",
    "draw_dashed_vertical",
    "draw_sequence_arrow",
    "extract_mermaid_label",
    "flush_bullets",
    "flush_code",
    "flush_paragraph",
    "is_table_divider",
    "load_font",
    "make_cell",
    "parse_edges",
    "pick_font",
    "prepare_mermaid_for_pdf",
    "register_fonts",
    "render_flowchart",
    "render_mermaid_image",
    "render_mermaid_with_cli",
    "render_sequence",
    "render_state",
    "render_xychart",
    "resolve_mermaid_viewport",
    "set_mermaid_dir",
    "set_quiet",
    "split_table_row",
    "text_size",
    "try_render_mermaid_with_cli",
    "wrap_text",
]
